// Deploys PolkaArena and hands the frontend everything it needs to talk to it.
//
//   pnpm deploy:testnet     (needs PRIVATE_KEY in contracts/.env and PAS in that account)
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

const GENERATED_DIR = path.join(__dirname, "..", "..", "web", "src", "generated");

async function main() {
  const { ethers, network } = hre;

  const signers = await ethers.getSigners();
  if (signers.length === 0) {
    throw new Error(
      `No account configured for network "${network.name}".\n` +
        `Put PRIVATE_KEY=0x... in contracts/.env, then fund that address at https://faucet.polkadot.io/`,
    );
  }

  const deployer = signers[0];
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`network  ${network.name} (chainId ${network.config.chainId ?? "local"})`);
  console.log(`deployer ${deployer.address}`);
  console.log(`balance  ${ethers.formatEther(balance)} ${network.name.includes("Testnet") ? "PAS" : "ETH"}`);

  if (balance === 0n) {
    throw new Error(
      `${deployer.address} has no balance. Get testnet PAS at https://faucet.polkadot.io/ and retry.`,
    );
  }

  const Arena = await ethers.getContractFactory("PolkaArena");
  console.log("\ndeploying PolkaArena...");
  const arena = await Arena.deploy();
  await arena.waitForDeployment();

  const address = await arena.getAddress();
  console.log(`deployed at ${address}`);

  writeFrontendBindings({ address, abi: Arena.interface.formatJson() });

  if (network.name === "polkadotHubTestnet") {
    console.log(`\nexplorer https://blockscout-testnet.polkadot.io/address/${address}`);
  }
  console.log(`\nwrote web/src/generated/ — the frontend will pick this up on its next reload.`);
}

/// The ABI is committed so a fresh clone builds without deploying first; the
/// address lives in .env.local so a redeploy never means editing source.
function writeFrontendBindings({ address, abi }) {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(GENERATED_DIR, "abi.ts"),
    `// Generated by contracts/scripts/deploy.js — do not edit by hand.\n` +
      `export const polkaArenaAbi = ${abi} as const;\n`,
  );

  const envPath = path.join(__dirname, "..", "..", "web", ".env.local");
  fs.writeFileSync(envPath, `VITE_ARENA_ADDRESS=${address}\n`);
  console.log(`wrote web/.env.local (VITE_ARENA_ADDRESS)`);
}

main().catch((error) => {
  console.error(`\n${error.message}`);
  process.exitCode = 1;
});
